//! Glyph names and simple-font encodings, for turning text-showing
//! operators back into Unicode.
//!
//! The glyph list is the part of the Adobe Glyph List that fonts in
//! circulation actually use (Latin, punctuation, symbols, Greek, Cyrillic
//! basics); `uniXXXX` and `uXXXX` names are decoded arithmetically.

/// Unicode for a glyph name, if known.
pub fn glyph_to_char(name: &str) -> Option<char> {
    if let Some(hex) = name.strip_prefix("uni") {
        if hex.len() >= 4 {
            if let Ok(v) = u32::from_str_radix(&hex[..4], 16) {
                return char::from_u32(v);
            }
        }
    }
    if let Some(hex) = name.strip_prefix('u') {
        if (4..=6).contains(&hex.len()) && hex.chars().all(|c| c.is_ascii_hexdigit()) {
            if let Ok(v) = u32::from_str_radix(hex, 16) {
                return char::from_u32(v);
            }
        }
    }
    // Names like "a.sc", "one.oldstyle": use the base name.
    let base = name.split('.').next().unwrap_or(name);
    if base.len() == 1 {
        return base.chars().next();
    }
    AGL.iter().find(|(n, _)| *n == base).map(|(_, c)| *c)
}

static AGL: &[(&str, char)] = &[
    ("AE", 'Æ'),
    ("Aacute", 'Á'),
    ("Abreve", 'Ă'),
    ("Acircumflex", 'Â'),
    ("Adieresis", 'Ä'),
    ("Agrave", 'À'),
    ("Alpha", 'Α'),
    ("Amacron", 'Ā'),
    ("Aogonek", 'Ą'),
    ("Aring", 'Å'),
    ("Atilde", 'Ã'),
    ("Beta", 'Β'),
    ("Cacute", 'Ć'),
    ("Ccaron", 'Č'),
    ("Ccedilla", 'Ç'),
    ("Chi", 'Χ'),
    ("Dcaron", 'Ď'),
    ("Dcroat", 'Đ'),
    ("Delta", 'Δ'),
    ("ETH", 'Ð'),
    ("Eacute", 'É'),
    ("Ecaron", 'Ě'),
    ("Ecircumflex", 'Ê'),
    ("Edieresis", 'Ë'),
    ("Egrave", 'È'),
    ("Emacron", 'Ē'),
    ("Eogonek", 'Ę'),
    ("Epsilon", 'Ε'),
    ("Eta", 'Η'),
    ("Eth", 'Ð'),
    ("Euro", '€'),
    ("Gamma", 'Γ'),
    ("Gbreve", 'Ğ'),
    ("Iacute", 'Í'),
    ("Icircumflex", 'Î'),
    ("Idieresis", 'Ï'),
    ("Idotaccent", 'İ'),
    ("Igrave", 'Ì'),
    ("Imacron", 'Ī'),
    ("Iota", 'Ι'),
    ("Kappa", 'Κ'),
    ("Lambda", 'Λ'),
    ("Lacute", 'Ĺ'),
    ("Lcaron", 'Ľ'),
    ("Lslash", 'Ł'),
    ("Mu", 'Μ'),
    ("Nacute", 'Ń'),
    ("Ncaron", 'Ň'),
    ("Ntilde", 'Ñ'),
    ("Nu", 'Ν'),
    ("OE", 'Œ'),
    ("Oacute", 'Ó'),
    ("Ocircumflex", 'Ô'),
    ("Odieresis", 'Ö'),
    ("Ograve", 'Ò'),
    ("Ohungarumlaut", 'Ő'),
    ("Omacron", 'Ō'),
    ("Omega", 'Ω'),
    ("Omicron", 'Ο'),
    ("Oslash", 'Ø'),
    ("Otilde", 'Õ'),
    ("Phi", 'Φ'),
    ("Pi", 'Π'),
    ("Psi", 'Ψ'),
    ("Racute", 'Ŕ'),
    ("Rcaron", 'Ř'),
    ("Rho", 'Ρ'),
    ("Sacute", 'Ś'),
    ("Scaron", 'Š'),
    ("Scedilla", 'Ş'),
    ("Sigma", 'Σ'),
    ("Tau", 'Τ'),
    ("Tcaron", 'Ť'),
    ("Theta", 'Θ'),
    ("Thorn", 'Þ'),
    ("Uacute", 'Ú'),
    ("Ucircumflex", 'Û'),
    ("Udieresis", 'Ü'),
    ("Ugrave", 'Ù'),
    ("Uhungarumlaut", 'Ű'),
    ("Umacron", 'Ū'),
    ("Upsilon", 'Υ'),
    ("Uring", 'Ů'),
    ("Xi", 'Ξ'),
    ("Yacute", 'Ý'),
    ("Ydieresis", 'Ÿ'),
    ("Zacute", 'Ź'),
    ("Zcaron", 'Ž'),
    ("Zdotaccent", 'Ż'),
    ("Zeta", 'Ζ'),
    ("aacute", 'á'),
    ("abreve", 'ă'),
    ("acircumflex", 'â'),
    ("acute", '´'),
    ("adieresis", 'ä'),
    ("ae", 'æ'),
    ("agrave", 'à'),
    ("alpha", 'α'),
    ("amacron", 'ā'),
    ("ampersand", '&'),
    ("angle", '∠'),
    ("aogonek", 'ą'),
    ("apostrophe", '\''),
    ("approxequal", '≈'),
    ("aring", 'å'),
    ("arrowdown", '↓'),
    ("arrowleft", '←'),
    ("arrowright", '→'),
    ("arrowup", '↑'),
    ("asciicircum", '^'),
    ("asciitilde", '~'),
    ("asterisk", '*'),
    ("at", '@'),
    ("atilde", 'ã'),
    ("backslash", '\\'),
    ("bar", '|'),
    ("beta", 'β'),
    ("braceleft", '{'),
    ("braceright", '}'),
    ("bracketleft", '['),
    ("bracketright", ']'),
    ("breve", '˘'),
    ("brokenbar", '¦'),
    ("bullet", '•'),
    ("bulletoperator", '∙'),
    ("cacute", 'ć'),
    ("caron", 'ˇ'),
    ("ccaron", 'č'),
    ("ccedilla", 'ç'),
    ("cedilla", '¸'),
    ("cent", '¢'),
    ("checkmark", '✓'),
    ("chi", 'χ'),
    ("circlemultiply", '⊗'),
    ("circleplus", '⊕'),
    ("circumflex", 'ˆ'),
    ("colon", ':'),
    ("comma", ','),
    ("congruent", '≅'),
    ("copyright", '©'),
    ("currency", '¤'),
    ("dagger", '†'),
    ("daggerdbl", '‡'),
    ("dcaron", 'ď'),
    ("dcroat", 'đ'),
    ("degree", '°'),
    ("delta", 'δ'),
    ("diamond", '◊'),
    ("dieresis", '¨'),
    ("divide", '÷'),
    ("dollar", '$'),
    ("dotaccent", '˙'),
    ("dotlessi", 'ı'),
    ("dotmath", '⋅'),
    ("eacute", 'é'),
    ("ecaron", 'ě'),
    ("ecircumflex", 'ê'),
    ("edieresis", 'ë'),
    ("egrave", 'è'),
    ("eight", '8'),
    ("element", '∈'),
    ("ellipsis", '…'),
    ("emacron", 'ē'),
    ("emdash", '—'),
    ("emptyset", '∅'),
    ("endash", '–'),
    ("eogonek", 'ę'),
    ("epsilon", 'ε'),
    ("equal", '='),
    ("equivalence", '≡'),
    ("estimated", '℮'),
    ("eta", 'η'),
    ("eth", 'ð'),
    ("exclam", '!'),
    ("exclamdown", '¡'),
    ("existential", '∃'),
    ("ff", 'ﬀ'),
    ("ffi", 'ﬃ'),
    ("ffl", 'ﬄ'),
    ("fi", 'ﬁ'),
    ("figuredash", '‒'),
    ("five", '5'),
    ("fl", 'ﬂ'),
    ("florin", 'ƒ'),
    ("four", '4'),
    ("fraction", '⁄'),
    ("franc", '₣'),
    ("gamma", 'γ'),
    ("gbreve", 'ğ'),
    ("germandbls", 'ß'),
    ("gradient", '∇'),
    ("grave", '`'),
    ("greater", '>'),
    ("greaterequal", '≥'),
    ("guillemotleft", '«'),
    ("guillemotright", '»'),
    ("guilsinglleft", '‹'),
    ("guilsinglright", '›'),
    ("heart", '♥'),
    ("hungarumlaut", '˝'),
    ("hyphen", '-'),
    ("iacute", 'í'),
    ("icircumflex", 'î'),
    ("idieresis", 'ï'),
    ("igrave", 'ì'),
    ("imacron", 'ī'),
    ("infinity", '∞'),
    ("integral", '∫'),
    ("intersection", '∩'),
    ("iota", 'ι'),
    ("kappa", 'κ'),
    ("lacute", 'ĺ'),
    ("lambda", 'λ'),
    ("lcaron", 'ľ'),
    ("less", '<'),
    ("lessequal", '≤'),
    ("logicaland", '∧'),
    ("logicalnot", '¬'),
    ("logicalor", '∨'),
    ("lozenge", '◊'),
    ("lslash", 'ł'),
    ("macron", '¯'),
    ("minus", '−'),
    ("minute", '′'),
    ("mu", 'µ'),
    ("multiply", '×'),
    ("nacute", 'ń'),
    ("ncaron", 'ň'),
    ("nine", '9'),
    ("notequal", '≠'),
    ("ntilde", 'ñ'),
    ("nu", 'ν'),
    ("numbersign", '#'),
    ("oacute", 'ó'),
    ("ocircumflex", 'ô'),
    ("odieresis", 'ö'),
    ("oe", 'œ'),
    ("ogonek", '˛'),
    ("ograve", 'ò'),
    ("ohungarumlaut", 'ő'),
    ("omacron", 'ō'),
    ("omega", 'ω'),
    ("omicron", 'ο'),
    ("one", '1'),
    ("onehalf", '½'),
    ("onequarter", '¼'),
    ("onesuperior", '¹'),
    ("ordfeminine", 'ª'),
    ("ordmasculine", 'º'),
    ("oslash", 'ø'),
    ("otilde", 'õ'),
    ("paragraph", '¶'),
    ("parenleft", '('),
    ("parenright", ')'),
    ("partialdiff", '∂'),
    ("percent", '%'),
    ("period", '.'),
    ("periodcentered", '·'),
    ("perthousand", '‰'),
    ("phi", 'φ'),
    ("pi", 'π'),
    ("plus", '+'),
    ("plusminus", '±'),
    ("product", '∏'),
    ("propersubset", '⊂'),
    ("propersuperset", '⊃'),
    ("proportional", '∝'),
    ("psi", 'ψ'),
    ("question", '?'),
    ("questiondown", '¿'),
    ("quotedbl", '"'),
    ("quotedblbase", '„'),
    ("quotedblleft", '“'),
    ("quotedblright", '”'),
    ("quoteleft", '‘'),
    ("quoteright", '’'),
    ("quotesinglbase", '‚'),
    ("quotesingle", '\''),
    ("racute", 'ŕ'),
    ("radical", '√'),
    ("rcaron", 'ř'),
    ("registered", '®'),
    ("rho", 'ρ'),
    ("ring", '˚'),
    ("sacute", 'ś'),
    ("scaron", 'š'),
    ("scedilla", 'ş'),
    ("second", '″'),
    ("section", '§'),
    ("semicolon", ';'),
    ("seven", '7'),
    ("sigma", 'σ'),
    ("sigma1", 'ς'),
    ("similar", '∼'),
    ("six", '6'),
    ("slash", '/'),
    ("space", ' '),
    ("sterling", '£'),
    ("summation", '∑'),
    ("tau", 'τ'),
    ("tcaron", 'ť'),
    ("therefore", '∴'),
    ("theta", 'θ'),
    ("thorn", 'þ'),
    ("three", '3'),
    ("threequarters", '¾'),
    ("threesuperior", '³'),
    ("tilde", '˜'),
    ("trademark", '™'),
    ("two", '2'),
    ("twosuperior", '²'),
    ("uacute", 'ú'),
    ("ucircumflex", 'û'),
    ("udieresis", 'ü'),
    ("ugrave", 'ù'),
    ("uhungarumlaut", 'ű'),
    ("umacron", 'ū'),
    ("underscore", '_'),
    ("union", '∪'),
    ("universal", '∀'),
    ("upsilon", 'υ'),
    ("uring", 'ů'),
    ("xi", 'ξ'),
    ("yacute", 'ý'),
    ("ydieresis", 'ÿ'),
    ("yen", '¥'),
    ("zacute", 'ź'),
    ("zcaron", 'ž'),
    ("zdotaccent", 'ż'),
    ("zero", '0'),
    ("zeta", 'ζ'),
];

/// StandardEncoding: code → char (None where undefined).
pub fn standard_encoding(code: u8) -> Option<char> {
    match code {
        0x20..=0x7E => Some(match code {
            0x27 => '’',
            0x60 => '‘',
            c => c as char,
        }),
        0xA1 => Some('¡'),
        0xA2 => Some('¢'),
        0xA3 => Some('£'),
        0xA4 => Some('⁄'),
        0xA5 => Some('¥'),
        0xA6 => Some('ƒ'),
        0xA7 => Some('§'),
        0xA8 => Some('¤'),
        0xA9 => Some('\''),
        0xAA => Some('“'),
        0xAB => Some('«'),
        0xAC => Some('‹'),
        0xAD => Some('›'),
        0xAE => Some('ﬁ'),
        0xAF => Some('ﬂ'),
        0xB1 => Some('–'),
        0xB2 => Some('†'),
        0xB3 => Some('‡'),
        0xB4 => Some('·'),
        0xB6 => Some('¶'),
        0xB7 => Some('•'),
        0xB8 => Some('‚'),
        0xB9 => Some('„'),
        0xBA => Some('”'),
        0xBB => Some('»'),
        0xBC => Some('…'),
        0xBD => Some('‰'),
        0xBF => Some('¿'),
        0xC1 => Some('`'),
        0xC2 => Some('´'),
        0xC3 => Some('ˆ'),
        0xC4 => Some('˜'),
        0xC5 => Some('¯'),
        0xC6 => Some('˘'),
        0xC7 => Some('˙'),
        0xC8 => Some('¨'),
        0xCA => Some('˚'),
        0xCB => Some('¸'),
        0xCD => Some('˝'),
        0xCE => Some('˛'),
        0xCF => Some('ˇ'),
        0xD0 => Some('—'),
        0xE1 => Some('Æ'),
        0xE3 => Some('ª'),
        0xE8 => Some('Ł'),
        0xE9 => Some('Ø'),
        0xEA => Some('Œ'),
        0xEB => Some('º'),
        0xF1 => Some('æ'),
        0xF5 => Some('ı'),
        0xF8 => Some('ł'),
        0xF9 => Some('ø'),
        0xFA => Some('œ'),
        0xFB => Some('ß'),
        _ => None,
    }
}

/// WinAnsiEncoding (cp1252): code → char.
pub fn winansi_encoding(code: u8) -> Option<char> {
    match code {
        0x20..=0x7E => Some(code as char),
        0xA0..=0xFF => char::from_u32(code as u32),
        0x80 => Some('€'),
        0x82 => Some('‚'),
        0x83 => Some('ƒ'),
        0x84 => Some('„'),
        0x85 => Some('…'),
        0x86 => Some('†'),
        0x87 => Some('‡'),
        0x88 => Some('ˆ'),
        0x89 => Some('‰'),
        0x8A => Some('Š'),
        0x8B => Some('‹'),
        0x8C => Some('Œ'),
        0x8E => Some('Ž'),
        0x91 => Some('‘'),
        0x92 => Some('’'),
        0x93 => Some('“'),
        0x94 => Some('”'),
        0x95 => Some('•'),
        0x96 => Some('–'),
        0x97 => Some('—'),
        0x98 => Some('˜'),
        0x99 => Some('™'),
        0x9A => Some('š'),
        0x9B => Some('›'),
        0x9C => Some('œ'),
        0x9E => Some('ž'),
        0x9F => Some('Ÿ'),
        _ => None,
    }
}

/// MacRomanEncoding: code → char.
pub fn macroman_encoding(code: u8) -> Option<char> {
    if (0x20..=0x7E).contains(&code) {
        return Some(code as char);
    }
    const HI: [char; 128] = [
        'Ä', 'Å', 'Ç', 'É', 'Ñ', 'Ö', 'Ü', 'á', 'à', 'â', 'ä', 'ã', 'å', 'ç', 'é', 'è', 'ê', 'ë',
        'í', 'ì', 'î', 'ï', 'ñ', 'ó', 'ò', 'ô', 'ö', 'õ', 'ú', 'ù', 'û', 'ü', '†', '°', '¢', '£',
        '§', '•', '¶', 'ß', '®', '©', '™', '´', '¨', '≠', 'Æ', 'Ø', '∞', '±', '≤', '≥', '¥', 'µ',
        '∂', '∑', '∏', 'π', '∫', 'ª', 'º', 'Ω', 'æ', 'ø', '¿', '¡', '¬', '√', 'ƒ', '≈', '∆', '«',
        '»', '…', '\u{A0}', 'À', 'Ã', 'Õ', 'Œ', 'œ', '–', '—', '“', '”', '‘', '’', '÷', '◊', 'ÿ',
        'Ÿ', '⁄', '€', '‹', '›', 'ﬁ', 'ﬂ', '‡', '·', '‚', '„', '‰', 'Â', 'Ê', 'Á', 'Ë', 'È', 'Í',
        'Î', 'Ï', 'Ì', 'Ó', 'Ô', '\u{F8FF}', 'Ò', 'Ú', 'Û', 'Ù', 'ı', 'ˆ', '˜', '¯', '˘', '˙', '˚',
        '¸', '˝', '˛', 'ˇ',
    ];
    if code >= 0x80 {
        Some(HI[(code - 0x80) as usize])
    } else {
        None
    }
}

/// Symbol font encoding for the characters that matter most (Greek and
/// common operators); others map to `None`.
pub fn symbol_encoding(code: u8) -> Option<char> {
    Some(match code {
        0x20 => ' ',
        0x21 => '!',
        0x22 => '∀',
        0x23 => '#',
        0x24 => '∃',
        0x25 => '%',
        0x26 => '&',
        0x27 => '∋',
        0x28 => '(',
        0x29 => ')',
        0x2A => '∗',
        0x2B => '+',
        0x2C => ',',
        0x2D => '−',
        0x2E => '.',
        0x2F => '/',
        0x30..=0x39 => code as char,
        0x3A => ':',
        0x3B => ';',
        0x3C => '<',
        0x3D => '=',
        0x3E => '>',
        0x3F => '?',
        0x40 => '≅',
        0x41 => 'Α',
        0x42 => 'Β',
        0x43 => 'Χ',
        0x44 => 'Δ',
        0x45 => 'Ε',
        0x46 => 'Φ',
        0x47 => 'Γ',
        0x48 => 'Η',
        0x49 => 'Ι',
        0x4A => 'ϑ',
        0x4B => 'Κ',
        0x4C => 'Λ',
        0x4D => 'Μ',
        0x4E => 'Ν',
        0x4F => 'Ο',
        0x50 => 'Π',
        0x51 => 'Θ',
        0x52 => 'Ρ',
        0x53 => 'Σ',
        0x54 => 'Τ',
        0x55 => 'Υ',
        0x56 => 'ς',
        0x57 => 'Ω',
        0x58 => 'Ξ',
        0x59 => 'Ψ',
        0x5A => 'Ζ',
        0x5B => '[',
        0x5C => '∴',
        0x5D => ']',
        0x5E => '⊥',
        0x5F => '_',
        0x60 => '‾',
        0x61 => 'α',
        0x62 => 'β',
        0x63 => 'χ',
        0x64 => 'δ',
        0x65 => 'ε',
        0x66 => 'φ',
        0x67 => 'γ',
        0x68 => 'η',
        0x69 => 'ι',
        0x6A => 'ϕ',
        0x6B => 'κ',
        0x6C => 'λ',
        0x6D => 'μ',
        0x6E => 'ν',
        0x6F => 'ο',
        0x70 => 'π',
        0x71 => 'θ',
        0x72 => 'ρ',
        0x73 => 'σ',
        0x74 => 'τ',
        0x75 => 'υ',
        0x76 => 'ϖ',
        0x77 => 'ω',
        0x78 => 'ξ',
        0x79 => 'ψ',
        0x7A => 'ζ',
        0x7B => '{',
        0x7C => '|',
        0x7D => '}',
        0x7E => '∼',
        0xA3 => '≤',
        0xA4 => '⁄',
        0xA5 => '∞',
        0xA9 => '♥',
        0xAB => '↔',
        0xAC => '←',
        0xAD => '↑',
        0xAE => '→',
        0xAF => '↓',
        0xB0 => '°',
        0xB1 => '±',
        0xB3 => '≥',
        0xB4 => '×',
        0xB5 => '∝',
        0xB6 => '∂',
        0xB7 => '•',
        0xB8 => '÷',
        0xB9 => '≠',
        0xBA => '≡',
        0xBB => '≈',
        0xBC => '…',
        0xC5 => '⊕',
        0xC7 => '∩',
        0xC8 => '∪',
        0xD0 => '∠',
        0xD1 => '∇',
        0xD2 => '®',
        0xD3 => '©',
        0xD4 => '™',
        0xD5 => '∏',
        0xD6 => '√',
        0xD7 => '⋅',
        0xD8 => '¬',
        0xD9 => '∧',
        0xDA => '∨',
        0xE5 => '∑',
        0xF2 => '∫',
        _ => return None,
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn names() {
        assert_eq!(glyph_to_char("eacute"), Some('é'));
        assert_eq!(glyph_to_char("uni20AC"), Some('€'));
        assert_eq!(glyph_to_char("u1F600"), Some('😀'));
        assert_eq!(glyph_to_char("a.sc"), Some('a'));
        assert_eq!(glyph_to_char("fi"), Some('ﬁ'));
        assert_eq!(glyph_to_char("g123"), None);
    }

    #[test]
    fn encodings() {
        assert_eq!(standard_encoding(0x27), Some('’'));
        assert_eq!(winansi_encoding(0x92), Some('’'));
        assert_eq!(macroman_encoding(0x8E), Some('é'));
        assert_eq!(symbol_encoding(0x61), Some('α'));
    }
}
